apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leave-service
  template:
    metadata:
      labels:
        app: leave-service
    spec:
      containers:
        - name: leave-api
          image: leaveacrprashant.azurecr.io/leave-service:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: leave-secrets
                  key: connection-string
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: leave-secrets
                  key: jwt-key
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: leave-config
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: leave-config
                  key: Jwt__Audience
            - name: Jwt__ExpiryMinutes
              valueFrom:
                configMapKeyRef:
                  name: leave-config
                  key: Jwt__ExpiryMinutes
            - name: DatabaseSettings__InitStrategy
              valueFrom:
                configMapKeyRef:
                  name: leave-config
                  key: DatabaseSettings__InitStrategy
            - name: EmployeeService__BaseUrl
              valueFrom:
                configMapKeyRef:
                  name: leave-config
                  key: EmployeeService__BaseUrl
---
apiVersion: v1
kind: Service
metadata:
  name: leave-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: leave-service
