apiVersion: v1
kind: Secret
metadata:
  name: leave-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded: Prashant1251@
  database-password: UHJhc2hhbnQxMjUxQA==
  
  # Base64 encoded: THIS_IS_A_SECRET_KEY_CHANGE_IT_MY_SECRET_KEY
  jwt-key: VEhJU19JU19BX1NFQ1JFVF9LRVlfQ0hBTkdFX0lUX01ZX1NFQ1JFVF9LRVk=

  # Base64 encoded: Host=postgres-db;Port=5432;Database=employeeleave;Username=postgres;Password=Prashant1251@
  connection-string: SG9zdD1wb3N0Z3Jlcy1kYjtQb3J0PTU0MzI7RGF0YWJhc2U9ZW1wbG95ZWVsZWF2ZTtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1QcmFzaGFudDEyNTFA
